#pragma once
#include "..\CL\Assert.h"

#define ENUMERATE_BYTECODES \
	__ENUMERATE_BYTECODE(_aaload, 0x32) \
	__ENUMERATE_BYTECODE(_aastore, 0x53) \
	__ENUMERATE_BYTECODE(_aconst_null, 0x01) \
	__ENUMERATE_BYTECODE(_aload, 0x19) \
	__ENUMERATE_BYTECODE(_aload_0, 0x2a) \
	__ENUMERATE_BYTECODE(_aload_1, 0x2b) \
	__ENUMERATE_BYTECODE(_aload_2, 0x2c) \
	__ENUMERATE_BYTECODE(_aload_3, 0x2d) \
	__ENUMERATE_BYTECODE(_anewarray, 0xbd) \
	__ENUMERATE_BYTECODE(_areturn, 0xb0) \
	__ENUMERATE_BYTECODE(_arraylength, 0xbe) \
	__ENUMERATE_BYTECODE(_astore, 0x3a) \
	__ENUMERATE_BYTECODE(_astore_0, 0x4b) \
	__ENUMERATE_BYTECODE(_astore_1, 0x4c) \
	__ENUMERATE_BYTECODE(_astore_2, 0x4d) \
	__ENUMERATE_BYTECODE(_astore_3, 0x4e) \
	__ENUMERATE_BYTECODE(_athrow, 0xbf) \
	__ENUMERATE_BYTECODE(_baload, 0x33) \
	__ENUMERATE_BYTECODE(_bastore, 0x54) \
	__ENUMERATE_BYTECODE(_bipush, 0x10) \
	__ENUMERATE_BYTECODE(_breakpoint, 0xca) \
	__ENUMERATE_BYTECODE(_caload, 0x34) \
	__ENUMERATE_BYTECODE(_castore, 0x55) \
	__ENUMERATE_BYTECODE(_checkcast, 0xc0) \
	__ENUMERATE_BYTECODE(_d2f, 0x90) \
	__ENUMERATE_BYTECODE(_d2i, 0x8e) \
	__ENUMERATE_BYTECODE(_d2l, 0x8f) \
	__ENUMERATE_BYTECODE(_dadd, 0x63) \
	__ENUMERATE_BYTECODE(_daload, 0x31) \
	__ENUMERATE_BYTECODE(_dastore, 0x52) \
	__ENUMERATE_BYTECODE(_dcmpg, 0x98) \
	__ENUMERATE_BYTECODE(_dcmpl, 0x97) \
	__ENUMERATE_BYTECODE(_dconst_0, 0x0e) \
	__ENUMERATE_BYTECODE(_dconst_1, 0x0f) \
	__ENUMERATE_BYTECODE(_ddiv, 0x6f) \
	__ENUMERATE_BYTECODE(_dload, 0x18) \
	__ENUMERATE_BYTECODE(_dload_0, 0x26) \
	__ENUMERATE_BYTECODE(_dload_1, 0x27) \
	__ENUMERATE_BYTECODE(_dload_2, 0x28) \
	__ENUMERATE_BYTECODE(_dload_3, 0x29) \
	__ENUMERATE_BYTECODE(_dmul, 0x6b) \
	__ENUMERATE_BYTECODE(_dneg, 0x77) \
	__ENUMERATE_BYTECODE(_drem, 0x73) \
	__ENUMERATE_BYTECODE(_dreturn, 0xaf) \
	__ENUMERATE_BYTECODE(_dstore, 0x39) \
	__ENUMERATE_BYTECODE(_dstore_0, 0x47) \
	__ENUMERATE_BYTECODE(_dstore_1, 0x48) \
	__ENUMERATE_BYTECODE(_dstore_2, 0x49) \
	__ENUMERATE_BYTECODE(_dstore_3, 0x4a) \
	__ENUMERATE_BYTECODE(_dsub, 0x67) \
	__ENUMERATE_BYTECODE(_dup, 0x59) \
	__ENUMERATE_BYTECODE(_dup_x1, 0x5a) \
	__ENUMERATE_BYTECODE(_dup_x2, 0x5b) \
	__ENUMERATE_BYTECODE(_dup2, 0x5c) \
	__ENUMERATE_BYTECODE(_dup2_x1, 0x5d) \
	__ENUMERATE_BYTECODE(_dup2_x2, 0x5e) \
	__ENUMERATE_BYTECODE(_f2d, 0x8d) \
	__ENUMERATE_BYTECODE(_f2i, 0x8b) \
	__ENUMERATE_BYTECODE(_f2l, 0x8c) \
	__ENUMERATE_BYTECODE(_fadd, 0x62) \
	__ENUMERATE_BYTECODE(_faload, 0x30) \
	__ENUMERATE_BYTECODE(_fastore, 0x51) \
	__ENUMERATE_BYTECODE(_fcmpg, 0x96) \
	__ENUMERATE_BYTECODE(_fcmpl, 0x95) \
	__ENUMERATE_BYTECODE(_fconst_0, 0x0b) \
	__ENUMERATE_BYTECODE(_fconst_1, 0x0c) \
	__ENUMERATE_BYTECODE(_fconst_2, 0x0d) \
	__ENUMERATE_BYTECODE(_fdiv, 0x6e) \
	__ENUMERATE_BYTECODE(_fload, 0x17) \
	__ENUMERATE_BYTECODE(_fload_0, 0x22) \
	__ENUMERATE_BYTECODE(_fload_1, 0x23) \
	__ENUMERATE_BYTECODE(_fload_2, 0x24) \
	__ENUMERATE_BYTECODE(_fload_3, 0x25) \
	__ENUMERATE_BYTECODE(_fmul, 0x6a) \
	__ENUMERATE_BYTECODE(_fneg, 0x76) \
	__ENUMERATE_BYTECODE(_frem, 0x72) \
	__ENUMERATE_BYTECODE(_freturn, 0xae) \
	__ENUMERATE_BYTECODE(_fstore, 0x38) \
	__ENUMERATE_BYTECODE(_fstore_0, 0x43) \
	__ENUMERATE_BYTECODE(_fstore_1, 0x44) \
	__ENUMERATE_BYTECODE(_fstore_2, 0x45) \
	__ENUMERATE_BYTECODE(_fstore_3, 0x46) \
	__ENUMERATE_BYTECODE(_fsub, 0x66) \
	__ENUMERATE_BYTECODE(_getfield, 0xb4) \
	__ENUMERATE_BYTECODE(_getstatic, 0xb2) \
	__ENUMERATE_BYTECODE(_goto, 0xa7) \
	__ENUMERATE_BYTECODE(_goto_w, 0xc8) \
	__ENUMERATE_BYTECODE(_i2b, 0x91) \
	__ENUMERATE_BYTECODE(_i2c, 0x92) \
	__ENUMERATE_BYTECODE(_i2d, 0x87) \
	__ENUMERATE_BYTECODE(_i2f, 0x86) \
	__ENUMERATE_BYTECODE(_i2l, 0x85) \
	__ENUMERATE_BYTECODE(_i2s, 0x93) \
	__ENUMERATE_BYTECODE(_iadd, 0x60) \
	__ENUMERATE_BYTECODE(_iaload, 0x2e) \
	__ENUMERATE_BYTECODE(_iand, 0x7e) \
	__ENUMERATE_BYTECODE(_iastore, 0x4f) \
	__ENUMERATE_BYTECODE(_iconst_m1, 0x02) \
	__ENUMERATE_BYTECODE(_iconst_0, 0x03) \
	__ENUMERATE_BYTECODE(_iconst_1, 0x04) \
	__ENUMERATE_BYTECODE(_iconst_2, 0x05) \
	__ENUMERATE_BYTECODE(_iconst_3, 0x06) \
	__ENUMERATE_BYTECODE(_iconst_4, 0x07) \
	__ENUMERATE_BYTECODE(_iconst_5, 0x08) \
	__ENUMERATE_BYTECODE(_idiv, 0x6c) \
	__ENUMERATE_BYTECODE(_if_acmpeq, 0xa5) \
	__ENUMERATE_BYTECODE(_if_acmpne, 0xa6) \
	__ENUMERATE_BYTECODE(_if_icmpeq, 0x9f) \
	__ENUMERATE_BYTECODE(_if_icmpge, 0xa2) \
	__ENUMERATE_BYTECODE(_if_icmpgt, 0xa3) \
	__ENUMERATE_BYTECODE(_if_icmple, 0xa4) \
	__ENUMERATE_BYTECODE(_if_icmplt, 0xa1) \
	__ENUMERATE_BYTECODE(_if_icmpne, 0xa0) \
	__ENUMERATE_BYTECODE(_ifeq, 0x99) \
	__ENUMERATE_BYTECODE(_ifge, 0x9c) \
	__ENUMERATE_BYTECODE(_ifgt, 0x9d) \
	__ENUMERATE_BYTECODE(_ifle, 0x9e) \
	__ENUMERATE_BYTECODE(_iflt, 0x9b) \
	__ENUMERATE_BYTECODE(_ifne, 0x9a) \
	__ENUMERATE_BYTECODE(_ifnonnull, 0xc7) \
	__ENUMERATE_BYTECODE(_ifnull, 0xc6) \
	__ENUMERATE_BYTECODE(_iinc, 0x84) \
	__ENUMERATE_BYTECODE(_iload, 0x15) \
	__ENUMERATE_BYTECODE(_iload_0, 0x1a) \
	__ENUMERATE_BYTECODE(_iload_1, 0x1b) \
	__ENUMERATE_BYTECODE(_iload_2, 0x1c) \
	__ENUMERATE_BYTECODE(_iload_3, 0x1d) \
	__ENUMERATE_BYTECODE(_impdep1, 0xfe) \
	__ENUMERATE_BYTECODE(_impdep2, 0xff) \
	__ENUMERATE_BYTECODE(_imul, 0x68) \
	__ENUMERATE_BYTECODE(_ineg, 0x74) \
	__ENUMERATE_BYTECODE(_instanceof, 0xc1) \
	__ENUMERATE_BYTECODE(_invokedynamic, 0xba) \
	__ENUMERATE_BYTECODE(_invokeinterface, 0xb9) \
	__ENUMERATE_BYTECODE(_invokespecial, 0xb7) \
	__ENUMERATE_BYTECODE(_invokestatic, 0xb8) \
	__ENUMERATE_BYTECODE(_invokevirtual, 0xb6) \
	__ENUMERATE_BYTECODE(_ior, 0x80) \
	__ENUMERATE_BYTECODE(_irem, 0x70) \
	__ENUMERATE_BYTECODE(_ireturn, 0xac) \
	__ENUMERATE_BYTECODE(_ishl, 0x78) \
	__ENUMERATE_BYTECODE(_ishr, 0x7a) \
	__ENUMERATE_BYTECODE(_istore, 0x36) \
	__ENUMERATE_BYTECODE(_istore_0, 0x3b) \
	__ENUMERATE_BYTECODE(_istore_1, 0x3c) \
	__ENUMERATE_BYTECODE(_istore_2, 0x3d) \
	__ENUMERATE_BYTECODE(_istore_3, 0x3e) \
	__ENUMERATE_BYTECODE(_isub, 0x64) \
	__ENUMERATE_BYTECODE(_iushr, 0x7c) \
	__ENUMERATE_BYTECODE(_ixor, 0x82) \
	__ENUMERATE_BYTECODE(_jsr, 0xa8) \
	__ENUMERATE_BYTECODE(_jsr_w, 0xc9) \
	__ENUMERATE_BYTECODE(_l2d, 0x8a) \
	__ENUMERATE_BYTECODE(_l2f, 0x89) \
	__ENUMERATE_BYTECODE(_l2i, 0x88) \
	__ENUMERATE_BYTECODE(_ladd, 0x61) \
	__ENUMERATE_BYTECODE(_laload, 0x2f) \
	__ENUMERATE_BYTECODE(_land, 0x7f) \
	__ENUMERATE_BYTECODE(_lastore, 0x50) \
	__ENUMERATE_BYTECODE(_lcmp, 0x94) \
	__ENUMERATE_BYTECODE(_lconst_0, 0x09) \
	__ENUMERATE_BYTECODE(_lconst_1, 0x0a) \
	__ENUMERATE_BYTECODE(_ldc, 0x12) \
	__ENUMERATE_BYTECODE(_ldc_w, 0x13) \
	__ENUMERATE_BYTECODE(_ldc2_w, 0x14) \
	__ENUMERATE_BYTECODE(_ldiv, 0x6d) \
	__ENUMERATE_BYTECODE(_lload, 0x16) \
	__ENUMERATE_BYTECODE(_lload_0, 0x1e) \
	__ENUMERATE_BYTECODE(_lload_1, 0x1f) \
	__ENUMERATE_BYTECODE(_lload_2, 0x20) \
	__ENUMERATE_BYTECODE(_lload_3, 0x21) \
	__ENUMERATE_BYTECODE(_lmul, 0x69) \
	__ENUMERATE_BYTECODE(_lneg, 0x75) \
	__ENUMERATE_BYTECODE(_lookupswitch, 0xab) \
	__ENUMERATE_BYTECODE(_lor, 0x81) \
	__ENUMERATE_BYTECODE(_lrem, 0x71) \
	__ENUMERATE_BYTECODE(_lreturn, 0xad) \
	__ENUMERATE_BYTECODE(_lshl, 0x79) \
	__ENUMERATE_BYTECODE(_lshr, 0x7b) \
	__ENUMERATE_BYTECODE(_lstore, 0x37) \
	__ENUMERATE_BYTECODE(_lstore_0, 0x3f) \
	__ENUMERATE_BYTECODE(_lstore_1, 0x40) \
	__ENUMERATE_BYTECODE(_lstore_2, 0x41) \
	__ENUMERATE_BYTECODE(_lstore_3, 0x42) \
	__ENUMERATE_BYTECODE(_lsub, 0x65) \
	__ENUMERATE_BYTECODE(_lushr, 0x7d) \
	__ENUMERATE_BYTECODE(_lxor, 0x83) \
	__ENUMERATE_BYTECODE(_monitorenter, 0xc2) \
	__ENUMERATE_BYTECODE(_monitorexit, 0xc3) \
	__ENUMERATE_BYTECODE(_multianewarray, 0xc5) \
	__ENUMERATE_BYTECODE(_new, 0xbb) \
	__ENUMERATE_BYTECODE(_newarray, 0xbc) \
	__ENUMERATE_BYTECODE(_nop, 0x00) \
	__ENUMERATE_BYTECODE(_pop, 0x57) \
	__ENUMERATE_BYTECODE(_pop2, 0x58) \
	__ENUMERATE_BYTECODE(_putfield, 0xb5) \
	__ENUMERATE_BYTECODE(_putstatic, 0xb3) \
	__ENUMERATE_BYTECODE(_ret, 0xa9) \
	__ENUMERATE_BYTECODE(_return, 0xb1) \
	__ENUMERATE_BYTECODE(_saload, 0x35) \
	__ENUMERATE_BYTECODE(_sastore, 0x56) \
	__ENUMERATE_BYTECODE(_sipush, 0x11) \
	__ENUMERATE_BYTECODE(_swap, 0x5f) \
	__ENUMERATE_BYTECODE(_tableswitch, 0xaa) \
	__ENUMERATE_BYTECODE(_wide, 0xc4)
namespace JVM
{
	enum class ByteCode
	{
#define __ENUMERATE_BYTECODE(x, y) x = y,
		ENUMERATE_BYTECODES
#undef __ENUMERATE_BYTECODE
	};

	const char* ByteCodeString(ByteCode bytecode);
}